// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4k0mA-GfydsN3FXOkXimUxWoIXk85vxc',
    appId: '1:976857623627:web:8a0040a193b0ec9c07b1ce',
    messagingSenderId: '976857623627',
    projectId: 'namaz-app-d0e52',
    authDomain: 'namaz-app-d0e52.firebaseapp.com',
    storageBucket: 'namaz-app-d0e52.firebasestorage.app',
    measurementId: 'G-VH2FXW2WSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDR5N9gXfw-M4dS-MWwpn8uD7moug3DK0',
    appId: '1:976857623627:android:d1ef0f819c95eae207b1ce',
    messagingSenderId: '976857623627',
    projectId: 'namaz-app-d0e52',
    storageBucket: 'namaz-app-d0e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOU1g_S9pfJLe4XfO2yRWdRmEfYRCU0MI',
    appId: '1:976857623627:ios:9b5524b6669ce03707b1ce',
    messagingSenderId: '976857623627',
    projectId: 'namaz-app-d0e52',
    storageBucket: 'namaz-app-d0e52.firebasestorage.app',
    iosBundleId: 'com.example.namazApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOU1g_S9pfJLe4XfO2yRWdRmEfYRCU0MI',
    appId: '1:976857623627:ios:9b5524b6669ce03707b1ce',
    messagingSenderId: '976857623627',
    projectId: 'namaz-app-d0e52',
    storageBucket: 'namaz-app-d0e52.firebasestorage.app',
    iosBundleId: 'com.example.namazApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4k0mA-GfydsN3FXOkXimUxWoIXk85vxc',
    appId: '1:976857623627:web:881ce40c6534235b07b1ce',
    messagingSenderId: '976857623627',
    projectId: 'namaz-app-d0e52',
    authDomain: 'namaz-app-d0e52.firebaseapp.com',
    storageBucket: 'namaz-app-d0e52.firebasestorage.app',
    measurementId: 'G-M36L3ECCTE',
  );
}
