class ManeviRehberData {
  static const List<String> ayetler = [
    "Namazı kılın, zekâtı verin. Rükû edenlerle birlikte siz de rükû edin. (Bakara, 43)",
    "Sabrederek ve namaz kılarak Allah’tan yardım dileyin. (Bakara, 45)",
    "Şüphesiz namaz, hayâsızlıktan ve kötülükten alıkoyar. (Ankebût, 45)",
    "Namazlara, özellikle orta namaza (ikindiye) devam edin. (Bakara, 238)",
    "Beni anmak için namaz kıl. (Tâhâ, 14)",
    "Sizin dostunuz ancak Allah’tır, Resulüdür ve namaz kılan müminlerdir. (Mâide, 55)",
    "Secde et ve yaklaş. (Alak, 19)",
    "Şüphesiz müminler kurtuluşa ermiştir; onlar ki namazlarında derin saygı içindedirler. (Mü’minûn, 1-2)",
    "Namaz müminler üzerine vakitleri belirlenmiş bir farzdır. (Nisâ, 103)",
    "Gündüzün iki tarafında ve gecenin gündüze yakın saatlerinde namaz kıl. (Hûd, 114)",
    "Onlar bollukta da darlıkta da Allah için harcarlar. (Âl-i İmrân, 134)",
    "Ancak sana kulluk eder ve yalnız senden yardım dileriz. (Fâtiha, 5)",
    "Ey iman edenler! Rükû edin, secde edin, Rabbinize kulluk edin. (Hac, 77)",
    "O, geceleyin secde ederek ve ayakta durarak boyun büken kimsedir. (Zümer, 9)",
    "Rabbin için namaz kıl ve kurban kes. (Kevser, 2)",
    "Huşu duyanlar için namaz ağır bir yük değildir. (Bakara, 45)",
    "Onlar namazlarını titizlikle koruyanlardır. (Mearic, 34)",
    "Rabbim! Beni ve soyumdan gelecekleri namazı devamlı kılanlardan eyle. (İbrahim, 40)",
    "Şüphesiz Allah, iyilik edenlerle beraberdir. (Ankebût, 69)",
    "O halde Rabbini hamd ile tesbih et ve secde edenlerden ol. (Hicr, 98)",
    "Ayaktayken, otururken ve yanlarınız üzerine yatarken Allah’ı zikredin. (Nisâ, 103)",
    "Allah, şükredenleri mükafatlandıracaktır. (Âl-i İmrân, 144)",
    "Gerçekten insan için çalışmasından başka bir şey yoktur. (Necm, 39)",
    "O, tövbeleri çokça kabul edendir. (Bakara, 37)",
    "İyiliklerin güzelliğiyle kötülükleri savın. (Ra'd, 22)",
  ];

  static const List<String> hadisler = [
    "Namaz dinin direğidir. (Tirmizî)",
    "Gözümün nuru namazdır. (Nesâî)",
    "Kulun Rabbine en yakın olduğu an secde anıdır. (Müslim)",
    "Cennetin anahtarı namazdır. (Tirmizî)",
    "Kıyamet günü kulun ilk sorguya çekileceği amel namazdır. (Taberânî)",
    "İki soğuk vaktin (Sabah ve İkindi) namazını kılan cennete girer. (Buhârî)",
    "Namaz nurdur. (Müslim)",
    "Abdest namazın anahtarıdır. (Ebû Dâvûd)",
    "Cemaatle kılınan namaz, yalnız kılınandan 27 derece daha faziletlidir. (Buhârî)",
    "Namaz günahlara kefarettir. (Müslim)",
    "Birinizin kapısının önünden nehir aksa ve günde 5 kez yıkansa, üzerinde kir kalır mı? (Buhârî)",
    "Allah katında amellerin en sevimlisi vaktinde kılınan namazdır. (Müslim)",
    "Yeryüzü bana mescit ve temiz kılındı. (Buhârî)",
    "Namazı terk edenle iman arasında sadece namaz vardır. (Tirmizî)",
    "Sabah namazının iki rekat sünneti, dünyadan ve içindekilerden daha hayırlıdır. (Müslim)",
    "Yatsı namazını cemaatle kılan, gecenin yarısını ibadetle geçirmiş gibidir. (Müslim)",
    "Allah temizdir, temizliği sever. (Tirmizî)",
    "Dua ibadetin özüdür. (Tirmizî)",
    "Ameller niyetlere göredir. (Buhârî)",
    "Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin. (Buhârî)",
    "Hayra vesile olan, o hayrı yapan gibidir. (Tirmizî)",
    "Müslüman elinden ve dilinden insanların emin olduğu kimsedir. (Buhârî)",
    "En hayırlınız, Kur'an'ı öğrenen ve öğretendir. (Buhârî)",
    "Gülümsemen bir sadakadır. (Tirmizî)",
    "Rabbine ibadet et ki kalbin huzur bulsun. (Hâkim)",
  ];

  static List<String> getAll() => [...ayetler, ...hadisler];
}
